openapi: 3.0.0
info:
  title: de:code 2020 Tech Quiz - Answer
  description: de:code 2020 Tech Quiz
  version: 1.0.0

servers:
  - url: '{logicAppsUrl}'
    description: LogicApps の受け入れURL
    variables:
      logicAppsUrl:
        default: <Input here>
        description: LogicApps の受入れURL

paths:
  /:
    post:
      operationId: answer
      summary: Send an answer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswerRequestBody'
      responses:
        '202':
          description: Accepted
          content:
            application/text:
              schema:
                type: string
    get:
      operationId: getCurrentQuestion
      summary: Get a current question
      responses:
        '200':
          description: Succeeded
          content:
            application/json:
              schema:
                $ref: './shared-components.yaml#/components/schemas/CurrentQuestion'

components:
  schemas:
    AnswerRequestBody:
      type: object
      properties:
        properties:
          type: object
          properties:
            identifier:
              type: string
              format: uuid
            question_id:
              type: string
            answer_id:
              type: string
              pattern: 'a|b|c|d'

